#!/usr/bin/env bash
# Entrypoint for the backend-neurai container.
#
# The .deb ships a neurai.conf tuned for a single host (daemon=1, RPC and ZMQ
# bound to 127.0.0.1). In a compose stack Blockbook runs in another container,
# so we derive a runtime config from the packaged one that:
#   * runs in the foreground and logs to stdout (docker logs),
#   * binds RPC/ZMQ on the container network and allows the docker subnets,
#   * optionally enables P2P listening.
# All other packaged settings (txindex, dbcache, zmq topics, ...) are kept.
#
# If the first argument is not a flag, it is executed instead of neuraid
# (e.g. `docker compose run --rm backend-neurai neurai-cli getblockchaininfo`).
set -euo pipefail

INSTALL_DIR=${NEURAI_INSTALL_DIR:-/opt/coins/nodes/neurai}
DATA_DIR=${NEURAI_DATA_DIR:-/opt/coins/data/neurai/backend}
RUN_DIR=${NEURAI_RUN_DIR:-/run/neurai}
SVC_USER=${NEURAI_USER:-neurai}
PKG_CONF=${INSTALL_DIR}/neurai.conf
RUNTIME_CONF=${RUN_DIR}/neurai.conf

RPC_BIND=${RPC_BIND:-0.0.0.0}
RPC_ALLOW_IP=${RPC_ALLOW_IP:-172.16.0.0/12 192.168.0.0/16 10.0.0.0/8}
ZMQ_BIND=${ZMQ_BIND:-0.0.0.0}
P2P_LISTEN=${P2P_LISTEN:-0}
RPC_USER=${RPC_USER:-}
RPC_PASS=${RPC_PASS:-}
NEURAID_EXTRA_ARGS=${NEURAID_EXTRA_ARGS:-}

log() { echo "[entrypoint] $*" >&2; }

# Run an arbitrary command if requested (anything that does not start with '-').
if [ "$#" -gt 0 ] && [ "${1#-}" = "$1" ]; then
    exec "$@"
fi

if [ ! -f "$PKG_CONF" ]; then
    log "packaged config not found: $PKG_CONF"; exit 1
fi

mkdir -p "$RUN_DIR" "$DATA_DIR"

# ZMQ port as packaged (falls back to the Neurai default used by blockbook).
zmq_port=$(sed -nE 's#^zmqpubhashblock=tcp://[^:]+:([0-9]+).*#\1#p' "$PKG_CONF" | head -n1)
zmq_port=${ZMQ_PORT:-${zmq_port:-38369}}

# ---------------------------------------------------------------------------
# Generate runtime config: packaged config minus the keys we override.
# ---------------------------------------------------------------------------
{
    grep -vE '^(daemon|printtoconsole|rpcbind|rpcallowip|zmqpub[a-z]+|listen|nolisten|pid)=' "$PKG_CONF"
    echo
    echo "# --- generated by docker entrypoint ---"
    echo "daemon=0"
    echo "printtoconsole=1"
    echo "rpcbind=${RPC_BIND}"
    echo "rpcallowip=127.0.0.1"
    for cidr in $RPC_ALLOW_IP; do echo "rpcallowip=${cidr}"; done
    echo "zmqpubhashtx=tcp://${ZMQ_BIND}:${zmq_port}"
    echo "zmqpubhashblock=tcp://${ZMQ_BIND}:${zmq_port}"
    if [ "$P2P_LISTEN" = "1" ]; then echo "listen=1"; else echo "listen=0"; fi
} > "$RUNTIME_CONF"

# Optional RPC credential override (must match the blockbook container).
if [ -n "$RPC_USER" ] || [ -n "$RPC_PASS" ]; then
    sed -i -E '/^(rpcuser|rpcpassword)=/d' "$RUNTIME_CONF"
    {
        if [ -n "$RPC_USER" ]; then echo "rpcuser=${RPC_USER}"; fi
        if [ -n "$RPC_PASS" ]; then echo "rpcpassword=${RPC_PASS}"; fi
    } >> "$RUNTIME_CONF"
fi

# ---------------------------------------------------------------------------
# Privileges: fix ownership (only when needed) and drop to the service user.
# ---------------------------------------------------------------------------
if [ "$(id -u)" = "0" ]; then
    uid=$(id -u "$SVC_USER"); gid=$(id -g "$SVC_USER")
    chown "$uid:$gid" "$RUN_DIR" "$RUNTIME_CONF"
    chmod 0640 "$RUNTIME_CONF"
    if [ "$(stat -c '%u' "$DATA_DIR")" != "$uid" ]; then
        log "fixing ownership of $DATA_DIR (this can take a while on large data dirs)"
        chown -R "$uid:$gid" "$DATA_DIR"
    fi
    run_as=(setpriv --reuid="$uid" --regid="$gid" --init-groups)
else
    run_as=()
fi

log "starting neuraid (conf=$RUNTIME_CONF datadir=$DATA_DIR rpcbind=$RPC_BIND zmq=tcp://${ZMQ_BIND}:${zmq_port} p2p_listen=$P2P_LISTEN)"
# shellcheck disable=SC2086
exec "${run_as[@]}" "${INSTALL_DIR}/neuraid" \
    -conf="$RUNTIME_CONF" \
    -datadir="$DATA_DIR" \
    -pid="${RUN_DIR}/neurai.pid" \
    $NEURAID_EXTRA_ARGS "$@"
